n_class: 20
schema:
  f0: num
  f1: num
  f10: num
  f100: num
  f101: num
  f102: num
  f103: num
  f104: num
  f105: num
  f106: num
  f107: num
  f108: num
  f109: num
  f11: num
  f110: num
  f111: num
  f112: num
  f113: num
  f114: num
  f115: num
  f116: num
  f117: num
  f118: num
  f119: num
  f12: num
  f120: num
  f121: num
  f122: num
  f123: num
  f124: num
  f125: num
  f126: num
  f127: num
  f128: num
  f129: num
  f13: num
  f130: num
  f131: num
  f132: num
  f133: num
  f134: num
  f135: num
  f136: num
  f137: num
  f138: num
  f139: num
  f14: num
  f140: num
  f141: num
  f142: num
  f143: num
  f144: num
  f145: num
  f146: num
  f147: num
  f148: num
  f149: num
  f15: num
  f150: num
  f151: num
  f152: num
  f153: num
  f154: num
  f155: num
  f156: num
  f157: num
  f158: num
  f159: num
  f16: num
  f160: num
  f161: num
  f162: num
  f163: num
  f164: num
  f165: num
  f166: num
  f167: num
  f168: num
  f169: num
  f17: num
  f170: num
  f171: num
  f172: num
  f173: num
  f174: num
  f175: num
  f176: num
  f177: num
  f178: num
  f179: num
  f18: num
  f180: num
  f181: num
  f182: num
  f183: num
  f184: num
  f185: num
  f186: num
  f187: num
  f188: num
  f189: num
  f19: num
  f190: num
  f191: num
  f192: num
  f193: num
  f194: num
  f195: num
  f196: num
  f197: num
  f198: num
  f199: num
  f2: num
  f20: num
  f200: num
  f201: num
  f202: num
  f203: num
  f204: num
  f205: num
  f206: num
  f207: num
  f208: num
  f209: num
  f21: num
  f210: num
  f211: num
  f212: num
  f213: num
  f214: num
  f215: num
  f216: num
  f217: num
  f218: num
  f219: num
  f22: num
  f220: num
  f221: num
  f222: num
  f223: num
  f224: num
  f225: num
  f226: num
  f227: num
  f228: num
  f229: num
  f23: num
  f230: num
  f231: num
  f232: num
  f233: num
  f234: num
  f235: num
  f236: num
  f237: num
  f238: num
  f239: num
  f24: num
  f240: num
  f241: num
  f242: num
  f243: num
  f244: num
  f245: num
  f246: num
  f247: num
  f248: num
  f249: num
  f25: num
  f250: num
  f251: num
  f252: num
  f253: num
  f254: num
  f255: num
  f256: num
  f257: num
  f258: num
  f259: num
  f26: num
  f260: num
  f261: num
  f262: num
  f263: num
  f264: num
  f265: num
  f266: num
  f267: num
  f268: num
  f269: num
  f27: num
  f270: num
  f271: num
  f272: num
  f273: num
  f274: num
  f275: num
  f276: num
  f277: num
  f278: num
  f279: num
  f28: num
  f280: num
  f281: num
  f282: num
  f283: num
  f284: num
  f285: num
  f286: num
  f287: num
  f288: num
  f289: num
  f29: num
  f290: num
  f291: num
  f292: num
  f3: num
  f30: num
  f31: num
  f32: num
  f33: num
  f34: num
  f35: num
  f36: num
  f37: num
  f38: num
  f39: num
  f4: num
  f40: num
  f41: num
  f42: num
  f43: num
  f44: num
  f45: num
  f46: num
  f47: num
  f48: num
  f49: num
  f5: num
  f50: num
  f51: num
  f52: num
  f53: num
  f54: num
  f55: num
  f56: num
  f57: num
  f58: num
  f59: num
  f6: num
  f60: num
  f61: num
  f62: num
  f63: num
  f64: num
  f65: num
  f66: num
  f67: num
  f68: num
  f69: num
  f7: num
  f70: num
  f71: num
  f72: num
  f73: num
  f74: num
  f75: num
  f76: num
  f77: num
  f78: num
  f79: num
  f8: num
  f80: num
  f81: num
  f82: num
  f83: num
  f84: num
  f85: num
  f86: num
  f87: num
  f88: num
  f89: num
  f9: num
  f90: num
  f91: num
  f92: num
  f93: num
  f94: num
  f95: num
  f96: num
  f97: num
  f98: num
  f99: num
time_budget: 200
